version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./images:/app/images  # Monte le dossier local "images" dans /app/images du conteneur
      - ./resized_images:/app/resized_images  # Monte le dossier local "resized_images" dans /app/resized_images
      - ./output:/app/output  # du conteneur
    command: python app.py