version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./output:/app/output  # Monte le dossier local "output" dans /app/output du conteneur
      - ./images:/app/images  # Monte le dossier local "images" dans /app/images du conteneur
    command: python app.py